version: '3'
services:
    postfix:
        container_name: Postfix
        build: 
            context: .
            dockerfile: Dockerfile
        ports:
            - "25:25"
        networks:
            iaasir4all:
                ipv4_address: 192.168.100.2

networks:
  iaasir4all:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 192.168.100.0/24
