---
- hosts: all
  become: true
  tasks:
    - name: Instalación de Vagrant y VirtualBox
      apt: name={{ item }} update_cache=yes state=latest
      with_items:
          - vagrant
          - virtualbox
          - ansible
