---
- hosts: all
  become: true
  tasks:
    - include_vars: 'vars.yml'

    - name: Instalación de vsftpd
      apt: name=vsftpd update_cache=yes state=latest

    - name: Creando usuario
      user:
        name: '{{ usuario }}'
        password: '{{ password | password_hash("sha512") }}'
        state: present
        shell: /bin/bash
        system: no
        createhome: '{{ homeuser }}'

    - file:
        path: '{{ local_root }}/{{ usuario }}'
        state: directory
        owner: '{{ usuario }}'
        group: root
        mode: 0775
        recurse: yes

    - name: Añadiendo fichero de configuración
      template: src=datos/vsftpd.conf.j2 dest=/etc/vsftpd.conf
      notify:
        - Reiniciar vsftpd

  handlers:
    - name: Reiniciar vsftpd
      service: name=vsftpd state=restarted
