version: '3'
services:
    apache:
        container_name: Apache
        build: 
            context: .
            dockerfile: Dockerfile
        ports:
            - '80:80'
        volumes:
            - './web:/web'
        networks:
            iaasir4all:
                ipv4_address: 192.168.100.2

networks:
  iaasir4all:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 192.168.100.0/24

